### ISSUE TITLE
Invalid transaction when `session.newSession` is emitted

### ISSUE THREAD

**Issue by luispdm** [KILTprotocol/kilt-node#815]
Hi, [Laos](https://github.com/freeverseio/laos) developer here. There's something I want to share here that you might be unaware of.

We've been investigating an issue in our parachain that causes transactions to be invalid occasionally. This happens when `session.newSession` is emitted.

The issue comes from this line of `pallet-session`: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/session/src/lib.rs#L563. It's been reported in the polkadot-sdk repo https://github.com/paritytech/polkadot-sdk/issues/184 but it remains unresolved as of today.

We successfully reproduced the issue in your runtime using [Chopsticks](https://github.com/AcalaNetwork/chopsticks/) with the following modified configuration:
```yml
endpoint: wss://kilt.ibp.network/
mock-signature-host: true
db: ./kilt.db.sqlite
runtime-log-level: 5
port: 9999

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  ParachainStaking:
    Round:
      Current: 12640
      First: 7583016
      Length: 3
```

We've reduced the round length for testing purposes. For reference, this is the screenshot of the invalid transaction:
![kilt-tx-invalid](https://github.com/user-attachments/assets/6e531a39-452c-4331-b647-9213baf8ca1d)

And this is the screenshot of the newly produced block:
![kilt-no-remark-in-block](https://github.com/user-attachments/assets/4b965182-8a23-4fc9-8f47-3099da4a4f66)
As you can see, `system.remark` is not emitted.

[This](https://github.com/freeverseio/laos/issues/895) is the issue on our side, in case you want to keep track of it.

Thank you for your time.
